// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwnylcsybwzygzsoukzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3bnlsY3N5Ynd6eWd6c291a3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzc4MzgsImV4cCI6MjA1ODcxMzgzOH0.bJjlZAmcwOFMT5RGxL3WfMp_SHxpLO49hg4TX29DYEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);